version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZK_ADVERTISED_HOST_NAME: 127.0.0.1
      ZK_CONNECTION_TIMEOUT_MS: 6000
      ZK_SYNC_TIME_MS: 2000
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "kafka_docker:2:3"


